export const items = [
    {
        name: "Acne Cream",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: true,
        isTopRated: true,
        isRecommended: true,
    },
    {
        name: "Vitiligio Solution",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: true,
        isTopRated: false,
        isRecommended: true,
    },
    {
        name: "Ezcema Cream",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: true,
        isTopRated: true,
        isRecommended: false,
    },
    {
        name: "Sunburn Ointment",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: "$18.99",
        isPopular: true,
        isTopRated: true,
        isRecommended: false,
    },
    {
        name: "Psioriasis Cream",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: true,
        isRecommended: true,
    },
    {
        name: "Vitiligio Balm",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: true,
        isRecommended: false,
    },
    {
        name: "Vitiligio Treatment",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: true,
        isRecommended: false,
    },
    {
        name: "Ezcema Oil",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: true,
        isRecommended: true,
    },
    {
        name: "Sunburn Balm",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: true,
        isRecommended: false,
    },
    {
        name: "Sunburn Relief",
        info: "All Natural Ingredients",
        price: "$24.99",
        discountPrice: 0,
        isPopular: false,
        isTopRated: false,
        isRecommended: false,
    }
];